### ISSUE TITLE
Basic routing doesn't compile with Scala 2.11.0-M8

### ISSUE THREAD

**Issue by jbirch** [spray/spray#790]
The following example compiles fine in Scala 2.10.3

``` scala
trait MyService extends HttpService {
  val myRoute = {
    path("something") {
      complete("ok")
    }
  }
}
```

When updating to Scala 2.11.0-M8, the following compiler error is thrown:

```
[error] /home/jbirch/Workspace/fuckingaboutwithspray/src/main/scala/com/fuckingaroundwithspray/MyService.scala:25: type mismatch;
[error]  found   : String("ok")
[error]  required: spray.httpx.marshalling.ToResponseMarshallable
[error]       complete("ok")
[error]                ^
[error] one error found
[error] (compile:compile) Compilation failed
```

importing spray.httpx.marshalling.BasicMarshallers.StringMarshaller explicitly turns this into an unrecoverable scala.reflect.internal.FatalError during globalPhase=erasure

```
[trace] Stack trace suppressed: run last compile:compile for the full output.
[error] (compile:compile) scala.reflect.internal.FatalError: 
[error]   unrecoverable error
[error]      while compiling: /home/jbirch/Workspace/fuckingaboutwithspray/src/main/scala/com/fuckingaroundwithspray/FuckingService.scala
[error]         during phase: globalPhase=erasure, enteringPhase=posterasure
[error]      library version: version 2.11.0-M8
[error]     compiler version: version 2.11.0-M8
[error]   reconstructed args: -Ywarn-nullary-unit -Xlint -Xfatal-warnings -Ywarn-inaccessible -Ywarn-nullary-override -classpath /home/jbirch/Workspace/fuckingaboutwithspray/target/scala-2.11.0-M8/classes:/home/jbirch/.ivy2/cache/io.spray/spray-can/bundles/spray-can-1.2.0.jar:/home/jbirch/.ivy2/cache/io.spray/spray-io/bundles/spray-io-1.2.0.jar:/home/jbirch/.ivy2/cache/io.spray/spray-util/bundles/spray-util-1.2.0.jar:/home/jbirch/.ivy2/cache/io.spray/spray-http/bundles/spray-http-1.2.0.jar:/home/jbirch/.ivy2/cache/org.parboiled/parboiled-scala_2.10/bundles/parboiled-scala_2.10-1.1.6.jar:/home/jbirch/.ivy2/cache/org.parboiled/parboiled-core/bundles/parboiled-core-1.1.6.jar:/home/jbirch/.ivy2/cache/io.spray/spray-routing/bundles/spray-routing-1.2.0.jar:/home/jbirch/.ivy2/cache/io.spray/spray-httpx/bundles/spray-httpx-1.2.0.jar:/home/jbirch/.ivy2/cache/org.jvnet.mimepull/mimepull/jars/mimepull-1.9.3.jar:/home/jbirch/.ivy2/cache/com.chuusai/shapeless_2.10/jars/shapeless_2.10-1.2.4.jar:/home/jbirch/.ivy2/cache/com.typesafe.akka/akka-actor_2.11.0-M8/jars/akka-actor_2.11.0-M8-2.2.3.jar:/home/jbirch/.ivy2/cache/com.typesafe/config/bundles/config-1.0.2.jar -language:higherKinds -bootclasspath /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/netx.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/plugin.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/rhino.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/lib/jfr.jar:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.5.1.fc20.x86_64/jre/classes:/home/jbirch/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.0-M8.jar -Ywarn-infer-any -Ywarn-adapted-args
[error] 
[error]   last tree to typer: This(<$anon: Function0>)
[error]        tree position: line 25 of /home/jbirch/Workspace/fuckingaboutwithspray/src/main/scala/com/fuckingaroundwithspray/FuckingService.scala
[error]               symbol: final <$anon: Function0>
[error]    symbol definition: final class $anonfun extends AbstractFunction0 with Serializable (a ClassSymbol)
[error]       symbol package: com.fuckingaroundwithspray
[error]        symbol owners: <$anon: Function0> -> value myRoute -> class MyService$class
[error]            call site: method apply in package fuckingaroundwithspray
[error] 
[error] == Source file context for tree position ==
[error] 
[error]     22     import spray.httpx.marshalling.BasicMarshallers.StringMarshaller
[error]     23     path("") {
[error]     24       complete("You get NOTHING!")
[error]     25     }
[error]     26   }
[error]     27 }
[error] Total time: 1 s, completed Mar 2, 2014 12:04:08 AM
```

This seems to affect both spray 1.2.0 and 1.3-RC4, which makes me suspect it might actually be a Scala 2.11 bug, but I don't really know enough about Scala to isolate a minimal case to demonstrate this. When Akka is built against 2.11.0-RC1, I'll take this for a roll again.
